### ISSUE TITLE
League Checklist

### ISSUE THREAD

**Issue by philsturgeon** [thephpleague/html-to-markdown#15]
One of the League peoples made this checklist:

http://phppackagechecklist.com/

It's a solid list of good advice that packages should try to follow, based off of requirements we thought up for League packages.

So, take a look at that, but minimum is:

- [x] Use `League` as the PSR-4 autoloader namespace. Shove code in a `src` folder.
- [x] Adhere to PSR-2 as the coding style guide.
- [x] List on Packagist with `league` as the vendor namespace.
- [x] Write unit tests. Aim for at least 80% coverage in version 1.
- [x] DocBlock all the things.
- [x] Use Semantic Versioning to manage version numbers.
- [x] Keep a Changelog.
- [x] Use Travis-CI or Circle-CI to automatically check coding standards and run tests.
- [x] Have an extensive README.

**Comment by colinodell** [comment]
All checklist items have been completed - html-to-markdown is now officially part of the League!
